name: KitBuilder
version: 1.0
main: me.markiscool.kitbuilder.KitBuilderPlugin
api-version: 1.13
author: MarkIsCool
description: Build kits within game, fully customizable
softdepend: [Vault]
commands:
  kit:
    usage: /<command> <kit_name>
    description: Base kit command
  kits:
    usage: /<command>
    description: Gives you a list of kits
  createkit:
    usage: /<command> <kit_name>
    description: Creates a new kit
  editkit:
    usage: /<command> <kit_name>
    description: Opens the edit kit GUI
  kitbuilder:
    usage: /<command> [help]
    description: List of commands